DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE groups(
group_id SERIAL NOT NULL PRIMARY KEY,
group_name VARCHAR NOT NULL);

DROP TABLE IF EXISTS students CASCADE;
CREATE TABLE students(
student_id SERIAL NOT NULL PRIMARY KEY,
group_id INT REFERENCES GROUPS(GROUP_ID),
first_name VARCHAR NOT NULL,
last_name VARCHAR NOT NULL);

DROP TABLE IF EXISTS courses CASCADE;
CREATE TABLE courses(
course_id SERIAL NOT NULL PRIMARY KEY,
course_name VARCHAR NOT NULL,
course_description text);

DROP TABLE IF EXISTS students_courses CASCADE;
CREATE TABLE students_courses(
ID serial NOT NULL PRIMARY KEY,
STUDENT_ID INT REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
COURSE_ID INT  REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE ON UPDATE CASCADE)

