DROP TABLE IF EXISTS students_courses CASCADE;
CREATE TABLE students_courses(
ID serial NOT NULL PRIMARY KEY,
STUDENT_ID INT REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
COURSE_ID INT  REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE ON UPDATE CASCADE)


